const GET_COUNTRY_ALL = 'GET_COUNTRY_ALL';
const GET_COUNTRY_NAME = 'GET_COUNTRY_NAME';
const GET_COUNTRY_DETAIL = 'GET_COUNTRY_DETAIL';
const CLEAR_ALL = 'CLEAR_ALL';

module.exports = {
    GET_COUNTRY_ALL,
    GET_COUNTRY_NAME,
    GET_COUNTRY_DETAIL,
    CLEAR_ALL
    
}